name: Build with Nix
on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v4

      - name: Build gui flavour
        run: nix build .

      - name: Build terminal flavour
        run: nix build .#terminal

      - name: Run tests
        run: nix flake check
